---
# Hadolint configuration for Rustume
# https://github.com/hadolint/hadolint

ignored:
  # DL3008: Pin versions in apt get install
  # Disabled because pinned versions can become unavailable, breaking builds.
  # We use latest for base packages in reproducible base images.
  - DL3008

trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
