#!/usr/bin/env bash
set -euo pipefail

# Extract coverage percentages from the reports generated by coverage jobs.

format="${1:?coverage format is required: lcov or istanbul-summary}"
file="${2:?coverage file is required}"

if [[ ! -f "$file" ]]; then
	echo "Coverage file not found: $file" >&2
	exit 1
fi

percent() {
	local hit="$1"
	local found="$2"

	if [[ -n "$found" && "$found" -gt 0 ]]; then
		awk -v hit="$hit" -v found="$found" 'BEGIN { printf "%.2f", (hit / found) * 100 }'
	else
		printf "0.00"
	fi
}

sum_lcov_field() {
	local prefix="$1"

	{ grep -E "^${prefix}:" "$file" 2>/dev/null || true; } |
		cut -d: -f2 |
		awk '{ sum += $1 } END { print sum + 0 }'
}

write_output() {
	local key="$1"
	local value="$2"

	if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
		echo "${key}=${value}" >>"$GITHUB_OUTPUT"
	fi
}

case "$format" in
lcov)
	lf=$(sum_lcov_field "LF")
	lh=$(sum_lcov_field "LH")
	bf=$(sum_lcov_field "BRF")
	bh=$(sum_lcov_field "BRH")
	fnf=$(sum_lcov_field "FNF")
	fnh=$(sum_lcov_field "FNH")

	lines=$(percent "$lh" "$lf")
	branches=$(percent "$bh" "$bf")
	functions=$(percent "$fnh" "$fnf")
	statements=""
	;;
istanbul-summary)
	lines=$(jq -r '.total.lines.pct // empty' "$file")
	branches=$(jq -r '.total.branches.pct // empty' "$file")
	functions=$(jq -r '.total.functions.pct // empty' "$file")
	statements=$(jq -r '.total.statements.pct // empty' "$file")
	;;
*)
	echo "Unknown coverage format: $format" >&2
	exit 1
	;;
esac

write_output "lines-coverage" "$lines"
write_output "branches-coverage" "$branches"
write_output "functions-coverage" "$functions"
write_output "statements-coverage" "$statements"

printf 'Lines: %s%%\n' "$lines"
printf 'Branches: %s%%\n' "$branches"
printf 'Functions: %s%%\n' "$functions"
if [[ -n "$statements" ]]; then
	printf 'Statements: %s%%\n' "$statements"
fi
